### ISSUE TITLE
Ben 10 and Danny Phantom not seeing 2.5.4?

### ISSUE THREAD

**Issue by FiveNights21611** [Heroes-United/HeroesUnited#10]
I'm trying to make a modpack for streaming, but I'm having an issue where Ben 10 and Danny Phantom won't detect the core mod. But, when I backport them to the one it says, I get a crash saying the poses don't work. What's going on? 
1.16.5 Minecraft, forge version 36.2.39

**Comment by FiveNights21611** [comment]
Ben 10 is 0.2.3, Danny Phantom is 0.1

**Comment by ChappiePie** [comment]
use 2.5.3

**Comment by FiveNights21611** [comment]
I try, but then it throws the pose error.

**Comment by ChappiePie** [comment]
can u give a crash log in our discord server?

**Comment by FiveNights21611** [comment]
I can try, but it could take a bit.

**Comment by FiveNights21611** [comment]
which channel do I send it in?
