### ISSUE TITLE
I can´t play the Ben 10 Mod

### ISSUE THREAD

**Issue by oijesifhsoipiyge9pi9** [Heroes-United/HeroesUnited#9]
I can´t play the ben 10 mod version 0.2.3
It appears that I need version 2.5.37 of herosunited but im using the most recent on curseforge 2.5.4
Im at 1.16.5
<img width="960" alt="Captura de ecrã 2022-02-15 194809" src="https://user-images.githubusercontent.com/72999499/154138800-90cb6ee7-4cd1-44c8-a515-0cfddd05b2e2.png">

**Comment by ChappiePie** [comment]
Use 2.5.3 core
